"""sitecustomize.py - RuntimeGuard autostart for wsl-system-guard.

Auto-generated by runtime_guard.make_sitecustomize_content().
Disable with: RUNTIME_GUARD_AUTOSTART=0
"""

from __future__ import annotations

import atexit
import os

try:
    from runtime_guard import RuntimeGuard
except Exception:
    RuntimeGuard = None  # type: ignore[assignment]

_enabled = os.getenv("RUNTIME_GUARD_AUTOSTART", "1").strip().lower() not in {"0", "false", "no", "off"}
_guard = None

if RuntimeGuard is not None and _enabled:
    try:
        _posture_key = "RUNTIME_GUARD_POSTURE"
        if not os.environ.get(_posture_key, "").strip():
            os.environ[_posture_key] = "wsl_dev"
        _guard = RuntimeGuard(
            env_prefix='RUNTIME_GUARD',
            log_tag='wsl-system-guard',
            cooldown_s=30.0,
        )
        _guard.start_background_check(interval_s=30.0, stage='repo-autostart')
    except Exception:
        _guard = None


def _stop_guard() -> None:
    if _guard is not None:
        try:
            _guard.stop_background_check()
        except Exception:
            pass


atexit.register(_stop_guard)
